﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace WWPointPredictor
{
    public partial class WWPointMLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Calories", @"Calories"),new InputOutputColumnPair(@"Fat (g)", @"Fat (g)"),new InputOutputColumnPair(@"Carb (g)", @"Carb (g)"),new InputOutputColumnPair(@"Fiber (g)", @"Fiber (g)"),new InputOutputColumnPair(@"Protein (g)", @"Protein (g)")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Calories",@"Fat (g)",@"Carb (g)",@"Fiber (g)",@"Protein (g)"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.Sdca(l1Regularization:0.313042108391576F,l2Regularization:32768F,labelColumnName:@"P+ Unrounded",featureColumnName:@"Features"));

            return pipeline;
        }
    }
}
